kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-app
  namespace: rdr-test
  labels:
    regionaldr: test
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-app-new
  namespace: rdr-test
  labels:
    regionaldr: test
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ocs-storagecluster-cephfs-selinux-relabel
  volumeMode: Filesystem
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sftpgo
  namespace: rdr-test
  labels:
    regionaldr: test
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem
--- 
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sftpgo-users-pvc
  namespace: rdr-test
  labels:
    regionaldr: test
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem
