apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
  name: db-app-sa
  namespace: regionaldr-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
  name: db-app-sa-anyuid
subjects:
  - kind: ServiceAccount
    name: db-app-sa
    namespace: regionaldr-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:openshift:scc:custom
  namespace: regionaldr-test
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
rules:
  - apiGroups: ["security.openshift.io"]
    resources: ["securitycontextconstraints"]
    resourceNames: ["custom"]
    verbs: ["use"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
  name: system:openshift:scc:custom
  namespace: regionaldr-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:custom
subjects:
- kind: ServiceAccount
  name: db-app-sa
  namespace: regionaldr-test

