---
resources:
  - ../base
namespace: deployment-rbd
commonLabels:
  app: deployment-rbd
patches:
  - target:
      kind: DRPlacementControl
      name: drpc
    patch: |-
      - op: replace
        path: /spec/preferredCluster
        value: dr1
