kind: Deployment
apiVersion: apps/v1
metadata:
  name: sftpgo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: sftpgo
      app.kubernetes.io/name: sftpgo
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: sftpgo
        app.kubernetes.io/name: sftpgo
    spec:
      restartPolicy: Always
      serviceAccountName: db-app-sa
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsGroup: 0
        fsGroupChangePolicy: OnRootMismatch
        seLinuxOptions:
          type: spc_t
      containers:
        - resources:
            limits:
              cpu: '2'
              memory: 4G
            requests:
              cpu: 500m
              memory: 1G
          readinessProbe:
            httpGet:
              path: /healthz
              port: telemetry
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: sftpgo
          livenessProbe:
            httpGet:
              path: /healthz
              port: telemetry
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: SFTPGO_SFTPD__BINDINGS__0__PORT
              value: '2022'
            - name: SFTPGO_SFTPD__BINDINGS__0__ADDRESS
              value: 0.0.0.0
            - name: SFTPGO_HTTPD__BINDINGS__0__PORT
              value: '8080'
            - name: SFTPGO_HTTPD__BINDINGS__0__ADDRESS
              value: 0.0.0.0
            - name: SFTPGO_TELEMETRY__BIND_PORT
              value: '10000'
            - name: SFTPGO_TELEMETRY__BIND_ADDRESS
              value: 0.0.0.0
          securityContext: {}
          ports:
            - name: sftp
              containerPort: 2022
              protocol: TCP
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: telemetry
              containerPort: 10000
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: config
              readOnly: true
              mountPath: /etc/sftpgo/sftpgo.json
              subPath: sftpgo.json
            - name: sftpgo-volume
              mountPath: /var/lib/sftpgo
            - name: sftpg-data
              mountPath: /srv/sftpgo
            - name: sftpg-users
              mountPath: /srv/sftpgo-users
            - name: sftpg-data-new
              mountPath: /srv/sftpgo-new
          terminationMessagePolicy: File
          image: 'quay.io/prd/t24x-creg.ps1.platform.vpbank.cloud/sftpgo/sftpgo:v2.6.6-alpine'
          args:
            - sftpgo
            - serve
      serviceAccount: db-app-sa
      volumes:
        - name: config
          configMap:
            name: sftpgo
            defaultMode: 420
        - name: sftpgo-volume
          persistentVolumeClaim:
            claimName: sftpgo
        - name: sftpg-data
          persistentVolumeClaim:
            claimName: pvc-app
        - name: sftpg-users
          persistentVolumeClaim:
            claimName: sftpgo-users-pvc
        - name: sftpg-data-new
          persistentVolumeClaim:
            claimName: pvc-app-new
      dnsPolicy: ClusterFirst
