# Infrastructure for dr1-aug-27-26 site
# UDN subnet: 192.168.100.0/24
---
namespace: vm-static-ip
resources:
  - ../base
patches:
  # Rename namespace to vm-static-ip
  - target:
      kind: Namespace
      name: vm-cloudinit-static-ip
    patch: |-
      - op: replace
        path: /metadata/name
        value: vm-static-ip

  # Set site-specific UDN subnet
  - target:
      kind: UserDefinedNetwork
      name: primary-udn
    patch: |-
      - op: replace
        path: /spec/layer2/subnets
        value:
          - "192.168.100.0/24"
