apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vmtest-1
spec:
  dataVolumeTemplates:
    - metadata:
        labels:
          appName: vmtest-1
        name: vmtest-1-volume
      spec:
        sourceRef:
          kind: DataSource
          name: centos-stream9
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 30Gi
          storageClassName: ocs-storagecluster-ceph-rbd
  instancetype:
    name: u1.medium
  preference:
    name: centos-stream9
  running: true
  template:
    metadata:
      labels:
        network.kubevirt.io/headlessService: headless
    spec:
      domain:
        devices:
          autoattachPodInterface: false
          disks: []
          interfaces:
            - masquerade: {}
              name: default
      networks:
        - name: default
          pod: {}
      subdomain: headless
      volumes:
        - dataVolume:
            name: vmtest-1-volume
          name: rootdisk-vmtest-1
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              chpasswd:
                expire: false
              password: oh8t-7khw-mdhl
              user: centos
          name: cloudinitdisk
